#!/usr/bin/env python3
"""Fork (VinneyUK/shelf.nu): generates app/styles/dark.css.

Shelf has no dark colours of its own, so the dark theme remaps its palette
when <html> has the "dark" class. Edit the palettes below, then run:

    python3 scripts/dark-theme.py
"""
from pathlib import Path

bg = {
 'white':'#0f1216','gray-25':'#12161b','gray-50':'#161b22','gray-100':'#1c2229','gray-200':'#262d36','gray-300':'#343b45',
 'slate-50':'#161b22','slate-100':'#1c2229',
 'primary-25':'#1e1611','primary-50':'#2a1d14','primary-100':'#3a2718',
 'success-25':'#0f1f16','success-50':'#122a1c','success-100':'#163826',
 'error-25':'#24110f','error-50':'#2e1512','error-100':'#3d1b17',
 'warning-25':'#241a0b','warning-50':'#2e210d','warning-100':'#3d2c10',
 'indigo-50':'#1a1b33','blue-50':'#0f1b2d','purple-50':'#1f1530','green-50':'#122a1c','red-50':'#2e1512','yellow-50':'#2e210d','orange-50':'#2a1d14',
}
text = {
 'black':'#f3f4f6','gray-900':'#f3f4f6','gray-800':'#e5e7eb','gray-700':'#d1d5db','gray-600':'#a1a8b3','gray-500':'#8b93a1','gray-400':'#6e7682','gray-300':'#4f5864',
 'slate-900':'#f3f4f6','slate-700':'#d1d5db',
 'success-700':'#4ade80','success-600':'#4ade80','error-700':'#f87171','error-600':'#f87171','warning-700':'#fbbf24','primary-700':'#f0a36b','primary-800':'#f4b887','indigo-700':'#a5b4fc',
}
border = {'white':'#262d36','gray-25':'#232a33','gray-50':'#232a33','gray-100':'#232a33','gray-200':'#2b333d','gray-300':'#39424d',
 'success-200':'#1f5a37','error-200':'#6b2a24','warning-200':'#6b4a12','primary-200':'#6b3f1f','primary-300':'#8a5229'}

def esc(cls): return cls.replace(':', '\\:').replace('/', '\\/').replace('.', '\\.').replace('!','\\!')
lines=['/* Fork (VinneyUK/shelf.nu): dark theme. Shelf has no dark colours of its own,',
       '   so this remaps its palette when <html> has the "dark" class.',
       '   GENERATED by scripts/dark-theme.py: edit the palette there and re-run it. */',
       'html.dark { color-scheme: dark; }',
       'html.dark body { background-color: #0f1216; color: #e5e7eb; }',
       'html.dark *, html.dark ::before, html.dark ::after { border-color: #2b333d; }',
       'html.dark input, html.dark textarea, html.dark select { background-color: #161b22; color: #f3f4f6; border-color: #39424d; }',
       'html.dark input::placeholder, html.dark textarea::placeholder { color: #6e7682; }',
       'html.dark [data-keep-light] { color-scheme: light; }',
       'html.dark ::-webkit-scrollbar { background: #12161b; } html.dark ::-webkit-scrollbar-thumb { background: #39424d; }',
       'html.dark [role="dialog"], html.dark [data-radix-popper-content-wrapper] > * { background-color: #161b22; }',
       'html.dark .shadow, html.dark .shadow-sm, html.dark .shadow-md, html.dark .shadow-lg, html.dark .shadow-xl { --tw-shadow-color: rgba(0,0,0,.6); --tw-shadow: var(--tw-shadow-colored); }',
]
def rule(sel, decl): lines.append(f'html.dark {sel} {{ {decl} }}')
for cls,col in bg.items():
    rule(f'.{esc("bg-"+cls)}', f'background-color: {col};')
    rule(f'.{esc("hover:bg-"+cls)}:hover', f'background-color: {col};')
    rule(f'.{esc("focus:bg-"+cls)}:focus', f'background-color: {col};')
    rule(f'.{esc("data-[state=open]:bg-"+cls)}[data-state=open]', f'background-color: {col};')
    rule(f'.{esc("md:bg-"+cls)}', f'background-color: {col};')
for cls,col in text.items():
    rule(f'.{esc("text-"+cls)}', f'color: {col};')
    rule(f'.{esc("hover:text-"+cls)}:hover', f'color: {col};')
for cls,col in border.items():
    rule(f'.{esc("border-"+cls)}', f'border-color: {col};')
    rule(f'.{esc("border-b-"+cls)}', f'border-bottom-color: {col};')
    rule(f'.{esc("border-t-"+cls)}', f'border-top-color: {col};')
    rule(f'.{esc("divide-"+cls)} > :not([hidden]) ~ :not([hidden])', f'border-color: {col};')
    rule(f'.{esc("ring-"+cls)}', f'--tw-ring-color: {col};')
    rule(f'.{esc("md:border-"+cls)}', f'border-color: {col};')
lines.append('html.dark .text-indigo-700 { color: #a5b4fc; }')
out = Path(__file__).resolve().parent.parent / 'app' / 'styles' / 'dark.css'
out.write_text('\n'.join(lines) + '\n')
print(f'{out}: {len(lines)} rules')
